
import { ExportData, DebugSolution, CodeFix, StructuredAnalysis } from '../types';

/**
 * Downloads a string content as a file in the browser.
 */
export function downloadBlob(content: string, filename: string, contentType: string) {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}

/**
 * Generates a standard diff-style patch from a set of code fixes.
 */
export function generatePatchFile(fixes: CodeFix[]): string {
  return fixes.map(fix => {
    return `--- ${fix.filePath}\n+++ ${fix.filePath}\n@@ -1,1 +1,1 @@\n-${fix.originalCode}\n+${fix.suggestedCode}\n`;
  }).join('\n');
}

/**
 * Generates a Jira ticket URL with pre-populated forensic context from structured analysis.
 */
export function generateJiraUrl(report: StructuredAnalysis): string {
  const ir = report?.incident_report;
  if (!ir) return "#";
  
  const failureName = ir.root_cause_analysis?.primary_failure || "Unknown Incident";
  const title = `[CloudLog AI] Incident: ${ir.severity || 'CRITICAL'} - ${failureName.substring(0, 50)}...`;
  const description = `
h1. Incident Summary
${failureName}

h2. Root Cause Analysis
${ir.root_cause_analysis?.description || "Description unavailable."}

h2. Impact Analysis
Mechanism: ${ir.root_cause_analysis?.mechanism || "N/A"}
Signature: ${ir.root_cause_analysis?.error_signature || "N/A"}

h2. Suggested Remediation
${(ir.remediation_plan?.steps || []).map(a => `* ${a}`).join('\n')}

----
_Generated by CloudLog AI Forensic Engine_
`;
  return `https://jira.atlassian.com/secure/CreateIssueDetails!default.jspa?pid=12345&issuetype=1&summary=${encodeURIComponent(title)}&description=${encodeURIComponent(description)}`;
}

/**
 * Formats a structured analysis report into a Markdown runbook for operational use.
 */
export function formatRunbook(report: StructuredAnalysis): string {
  const ir = report?.incident_report;
  if (!ir) return "No forensic report available.";

  const failureDesc = ir.root_cause_analysis?.description || "Description unavailable.";
  const failureName = ir.root_cause_analysis?.primary_failure || "Unknown Incident";
  
  return `
# OPERATIONAL RUNBOOK: ${ir.severity || 'UNKNOWN'}
## Incident: ${failureDesc}

### 1. Executive Summary
${failureName}

### 2. Remediation Steps
${(ir.remediation_plan?.steps || []).map((action, i) => `${i + 1}. ${action}`).join('\n')}

### 3. Verification Post-Fix
- Monitor log streams for pattern signatures.
- Ensure engine confidence remains > 90%

---
Generated by CloudLog AI Automation
`.trim();
}

/**
 * Generates a Markdown report summarizing a proposed debug solution.
 */
export function generateMarkdownIssue(solution: DebugSolution, stats: any): string {
  const fixesMd = solution.fixes.map(f => `
### Fix: ${f.title}
**File:** \`${f.filePath}\`
\`\`\`diff
- ${f.originalCode}
+ ${f.suggestedCode}
\`\`\`
**Explanation:** ${f.explanation}
`).join('\n');

  return `
# [CloudLog AI] Diagnostic Report: ${solution.strategy}

## Metadata
- **Log File:** ${stats?.fileName || 'Unknown'}
- **Engine Confidence:** ${(solution.confidence * 100).toFixed(0)}%
- **Root Cause:** ${solution.rootCause}

## Proposed Remediation
${fixesMd}

## Best Practices
${solution.bestPractices.map(bp => `- ${bp}`).join('\n')}

---
*Generated by CloudLog AI Diagnostic Hub*
`;
}

/**
 * Generates an HTML document representing the full diagnostic forensic report.
 */
export function generateHtmlReport(data: ExportData): string {
  const messagesHtml = data.messages.map(m => `
    <div style="margin-bottom: 20px; padding: 15px; background: ${m.role === 'user' ? '#f1f5f9' : '#fff'}; border: 1px solid #e2e8f0; border-radius: 8px;">
      <strong style="color: ${m.role === 'user' ? '#2563eb' : '#059669'}">${m.role.toUpperCase()}</strong>
      <div style="margin-top: 10px; white-space: pre-wrap;">${m.content}</div>
    </div>
  `).join('');

  return `
<!DOCTYPE html>
<html>
<head>
  <title>CloudLog AI Diagnostic Report</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #1e293b; max-width: 800px; margin: 40px auto; padding: 0 20px; }
    h1 { border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; font-style: italic; }
    .stats { display: grid; grid-template-cols: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin: 20px 0; }
    .stat-box { background: #f8fafc; padding: 15px; border-radius: 8px; border: 1px solid #e2e8f0; }
    .label { font-size: 10px; font-weight: 800; color: #64748b; text-transform: uppercase; letter-spacing: 0.1em; }
    .value { font-size: 18px; font-weight: 800; }
  </style>
</head>
<body>
  <h1>CLOUDLOG AI FORENSIC REPORT</h1>
  <p>Generated on: ${data.timestamp}</p>
  
  <div class="stats">
    <div class="stat-box">
      <div class="label">Source File</div>
      <div class="value">${data.stats?.fileName}</div>
    </div>
    <div class="stat-box">
      <div class="label">Total Entries</div>
      <div class="value">${data.stats?.totalEntries.toLocaleString()}</div>
    </div>
  </div>

  <h2>Diagnostic Timeline</h2>
  ${messagesHtml}

  <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #64748b; text-align: center;">
    End of CloudLog AI Automated Diagnostic Report
  </footer>
</body>
</html>
`;
}
